package com.gjj.pojo;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.recordId
     *
     * @mbggenerated
     */
    private Integer recordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ucode
     *
     * @mbggenerated
     */
    private String ucode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.recordId
     *
     * @return the value of user.recordId
     *
     * @mbggenerated
     */
    public Integer getRecordid() {
        return recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.recordId
     *
     * @param recordid the value for user.recordId
     *
     * @mbggenerated
     */
    public void setRecordid(Integer recordid) {
        this.recordid = recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ucode
     *
     * @return the value of user.ucode
     *
     * @mbggenerated
     */
    public String getUcode() {
        return ucode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ucode
     *
     * @param ucode the value for user.ucode
     *
     * @mbggenerated
     */
    public void setUcode(String ucode) {
        this.ucode = ucode == null ? null : ucode.trim();
    }
}